title: Blog
description: >-
  An awesome blog written by a Human in the AI era.
baseurl: ""
url: "https://ipravek.github.io/"
github_username:  ipravek

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: auto